config/routes.rb
Rails.application.routes.draw do
  get 'posts/index' => "posts#index", as:"p_index"
  get 'posts/new' => "posts#new", as:"p_new"
  post 'posts/create' => "posts#create", as:"p_create"
  
  get 'login' => "users#login_form", as:"login"
  get '/' => "users#new", as:"new"
  get 'index' => "users#index"
  get 'users/:id/edit' => "users#edit", as:"edit"
  get 'users/:id' => "users#show", as:"show"
  post 'users/create' => "users#create", as:"create"
  patch 'users/:id/update' => "users#update", as:"update"
  post 'users/:id/destroy' => "users#destroy", as:"destroy"
  post 'login' => "users#login", as:"log"
  post "logout" => "users#logout"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, {presence: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(content: params[:content])
    @post.save
    redirect_to("/posts/index")
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/index")
    end
  end
  
  def index
    @users = User.all.order(created_at: :desc)
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
   def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    # @user.email = params[:user][:email]
    # @user.save
    @user.update(update_user_params)
    puts "エラー: #{@user.errors.full_messages}"
    redirect_to("/index")
  end
  
 def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to("/index")
 end
 
 def login_form
 end
 
 def login
    @user = User.find_by(login_user_params)
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/index")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/login_form")
    end
  end
  
   def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end
 
 private
  def user_params
    # email: params[:email], password: params[:password]
    #params.permit(:email, :password)
    params.require(:user).permit(:email,:password)
  end
  
  def update_user_params
    params.require(:user).permit(:email)
  end
  
   def login_user_params
    params.require(:user).permit(:email,:password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserApp3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% if session[:user_id] %>
          <li>
            現在ログインしているユーザーのid:
      
            <%= session[:user_id] %>
            <%= button_to("ログアウト", "/logout", {method: "post"}) %>
          </li>
        <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

app/views/posts/new.html.erb
 

<h1>新規投稿</h1>

<%= form_with model: @post, url: p_create_path do |form| %>
        <label for="content"></label>
          <%= form.text_field :content %>
         
          <%= form.submit %>
<!--<% end %>-->

app/views/users/edit.html.erb
<!--<%#= form_tag("/users/#{@user.id}/update") do %>-->
<!--  <textarea name="email"><%#= @user.email %></textarea>-->
<!--    <input type="submit" value="保存">-->
<!--<%# end %>-->

<%= form_with model: @user, url: update_path(@user.id) do |form| %>
    <label for="email">email</label>
    <%= form.text_field :email %>
    <%= form.submit %> 
<% end %>
     

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%#= link_to(user.email,"/users/#{user.id}") %>
    <%= link_to user.email, show_path(user) %>
<% end %>

    <%= link_to "新規投稿", p_new_path(@post) %>
    <%= link_to "新規登録", new_path(@user) %>
    
    <%= link_to "ログイン", login_path(@user) %>

app/views/users/login_form.html.erb
<h1>ログイン</h1>
<% if @error_message %>
 <%= @error_message %>
<% end %>
<!--<%#= form_tag("/login") do %>-->
<!--  <p>メールアドレス</p>-->
<!--  <input name="email" value="<%#= @email %>">-->
<!--  <p>パスワード</p>-->
<!--  <input type="password" name="password" value="<%#= @password %>">-->
<!--  <input type="submit" value="ログイン">-->
<!--<%# end %>-->

<%= form_with model: @user, url: log_path do |form| %>
        <label for="email">email</label>
          <%= form.text_field :email %>
        <label for="password">password</label>
          <%= form.password_field :password %>
          <%= form.submit %>
<!--<% end %>-->

     
    

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= form_with model: @user, url: create_path do |form| %>
        <label for="email">email</label>
          <%= form.text_field :email %>
        <label for="password">password</label>
          <%= form.password_field :password %>
          <%= form.submit %>
<!--<% end %>-->

app/views/users/show.html.erb
<%= @user.email %>
<!--<%#= link_to("編集","/users/#{@user.id}/edit") %>-->
<%= link_to "編集", edit_path(@user) %>
<%= button_to("削除",destroy_path(@user.id), {method: "post"}) %>
<style>
    button {
        
    }
</style>